-- Tabla: ledger_last_send
-- Descripcion: Control de ultimo envio por ledger_key para TTL/rate-limit
-- Autor: Antay Consultoria
-- Fecha: 2026-02-15

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS ledger_last_send (
    ledger_key TEXT PRIMARY KEY,
    last_sent_at TIMESTAMP WITH TIME ZONE,
    last_msg_id TEXT,
    send_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ledger_last_send_last_sent_at ON ledger_last_send(last_sent_at);

DROP TRIGGER IF EXISTS update_ledger_last_send_updated_at ON ledger_last_send;
CREATE TRIGGER update_ledger_last_send_updated_at
    BEFORE UPDATE ON ledger_last_send
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE ledger_last_send IS 'Control de ultimo envio por ledger_key';
COMMENT ON COLUMN ledger_last_send.ledger_key IS 'Clave unica para evitar reenvios no deseados';
COMMENT ON COLUMN ledger_last_send.last_sent_at IS 'Timestamp del ultimo envio';

-- Tabla: send_attempts
-- Descripcion: Historial de intentos de envio por destinatario

CREATE TABLE IF NOT EXISTS send_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_key TEXT,
    recipient TEXT NOT NULL,
    status TEXT NOT NULL,
    reason TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now(),
    run_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_send_attempts_ledger_key ON send_attempts(ledger_key);
CREATE INDEX IF NOT EXISTS idx_send_attempts_recipient ON send_attempts(recipient);
CREATE INDEX IF NOT EXISTS idx_send_attempts_status ON send_attempts(status);
CREATE INDEX IF NOT EXISTS idx_send_attempts_timestamp ON send_attempts(timestamp);

COMMENT ON TABLE send_attempts IS 'Historial de intentos de envio de email/whatsapp';
COMMENT ON COLUMN send_attempts.recipient IS 'Destinatario del intento de envio';
COMMENT ON COLUMN send_attempts.status IS 'Estado del intento (SENT, FAILED, BLOCKED, etc)';
COMMENT ON COLUMN send_attempts.timestamp IS 'Timestamp del intento';
